### ISSUE TITLE
[Open in Temp Container] open-close loop with non-temp container - (compat issue MAC)  

### ISSUE THREAD

**Issue by knghtbrd** [igorlogius/igorlogius#47] opened 2024-09-14 15:55 UTC
### Steps to Reproduce

1. Create non-temporary container for website (say … Github for instance)
2. "Always open in" for some domain in that container (say https://github.com/ for instance)
3. Open a new tab aimed at the domain in question

### Expected Result

Expect new "Github" tab containing … Github.

### Actual Result

Github/Temp12345 tab repeatedly opening/closing each other 😱

### Additional Information

Firefox version is 130.0 (130.0-0.1 archlinux x86_64) and the extension just upgraded for me last night to 1.1.42. This only appears to trigger when Firefox attempts to open a non-temporary container. That is, if I open a new tab and search for something (temporary container) and I visit a website for which I do not have any permanent containers defined, everything lives inside a temporary container just fine.

Temporary container rules are Implicit with same origin policy in either state. No exclusions either from the implicit/explicit rules nor from TC as a whole are defined since I'd been using the fact that opening e.g. sites I'd defined as having an explicit container (things like Github, my email, certain shopping sites, etc.) and the fact that those tabs were limited to the websites in question was generally doing that job for me.

Tested specifically adding Github in particular to exclude from TC to see what'd happen since I know Github loads content from three or four other dmails while rendering any given page. That worked around the problem, but I think a proper fix here would be to ensure that you didn't kill a tab belonging to another container.

**Comment by igorlogius** [comment] 2024-09-14 16:26
i might have borked something ... i'll check

**Comment by igorlogius** [comment] 2024-09-14 16:36
So one issue was that OiTC did ignore the container bounderies ... when in implicit mode. When i refactored the code missed that case and accidentally squashed it.

That simple enough to fix ( i think ).

The thing with the reloading might be a sideeffect ... not sure, but lets see how it behaves after fixing the first issue here.

**Comment by knghtbrd** [comment] 2024-09-14 16:47
Glad it was easy to find at least part of the problem, if not the whole thing! 🙂

**Comment by igorlogius** [comment] 2024-09-14 16:51
@knghtbrd  Could you explain what do exactly when you say `Create non-temporary container for website `  

Do you right click and use `Open in New Container Tab` or are you using `MAC` to automatically open tabs with an assigned container?

**Comment by knghtbrd** [comment] 2024-09-14 17:37
I start out with creating a container, then I will open the page I want to add to the container and click "Always open in…" then select the new container. The next time I open that particular URL I'm usually asked whether I want to open that in Temp<whatever> or in the assigned container, along with the option to remember my choice. Under MAC → Manage → specific container there's the option to remove a domain added this way (but not add, not edit, not specify subdomains too…) and to limit the container to only the domains on the list (which would be a lot easier if not for the previous lack of an ADD button, c'mon Mozilla! *sigh*)

Looked up how to test a local extension (last time I did so was on a Chrome browser ages ago), so I can test a patch without doing things I don't understand. 😁

**Comment by igorlogius** [comment] 2024-09-14 18:35
Reverting is not an option because of another bug the update fixed, so the only viable solution for now, is to useOiTC's Exclusion list. 

My suggestion would be to switch from MAC to [Containerize](https://addons.mozilla.org/en-US/firefox/addon/containerise/) to manage your containers. 

Beside the fact that it IMO has a more streamlined UI for container assigments - can use also use a very similar regex-syntax as with OiTC which allows you mostly copy and paste the assigment expressions and keep them synced. 

Example Config for Github Comparison 

|Containerize| OiTC |
| --- | --- |
|`@^https:\/\/github\.com.* , Github` |`^https:\/\/github\.com.*` |

Sorry if thats not what you wished for, but i dont see a better solution at the moment.

**Comment by igorlogius** [comment] 2024-09-14 18:50
While users might be unhappy that OiTC doenst work "out-of-the box" with MAC i dont really see a good fix for this. 

Maybe i should add a warning when a user fist activates `implicit` mode that informs them about having to setup the Exclusions correctly if other addons that automatically manage urls/domains are used together with OiTC.

**Comment by silverwings15** [comment] 2024-09-15 02:54
i'm using OiTC's exclusion list, however I still have a variation of this issue:

- put Github into a permanent container using FMAC or Containerise
- use google (temp container) and search for github results
- middle click on a Github link from the results
- 2 tabs of the result are opened instead of just one
- if i simply left click on the result, only one tab appears, however the focus is then switched to the Github tab instead of remaining on the google tab.

Any ideas on solutions?

**Comment by silverwings15** [comment] 2024-09-15 03:26
actually, the problem seems to be that if you are browsing in a permanent container, and you middle click a link to a site that will be opened in a temporary container, the link will be opened twice, and vice versa

**Comment by knghtbrd** [comment] 2024-09-15 06:22
I was getting it even if I opened a new tab (no color yet) and typed the name of a domain that SHOULD open in a permanent container. There isn't an easy/fast way to export domain-container associations so I'm adding them to containerize as I go, but using Containerize's URL list instead of Firefox MAC's own seems to be working around the problem without explicit exclusions required (unless igorlogius has pushed out a patch that updated while I wasn't looking?)

I'll be switching to Containerize because editing the URL associations is a useful feature at the cost of some permanent tab hygiene and the searing white popup window Containerize uses. *sigh*

I think the bug label remains appropriate though considering that MAC isn't "just another extension", even if the recommendation at this time is to work around it by using something else to provide similar functionality. It's your bug tracker though.

Pending a better solution, I'm gonna go plead for dark mode support in Containerize for now. 😅 (BTW, since OiTC doesn't do dark mode either, thank you for mostly using a nice middle gray background in your preferences making it basically not really that important. In fact I've found OiTC very useful after the initial not understanding the settings issue. Thanks for creating it!)

**Comment by igorlogius** [comment] 2024-09-15 07:52
> i'm using OiTC's exclusion list, however I still have a variation of this issue:
> 
>     * put Github into a permanent container created by FMAC or Containerise
> 
>     * use google (temp container) and search for github results
> 
>     * middle click on a Github link from the results
> 
>     * 2 tabs of the result are opened instead of just one
> 
>     * if i simply left click on the result, only one tab appears, however the focus is then switched to the Github tab instead of staying on the google tab.
> 
> 
> Any ideas on solutions? I know the OG Temporary Containers didn't have this issue, or maybe it had some sort of options that I could choose to prevent this from happening (not sure as it's been a while that i had used it)

I'll see if i can reproduce the issue, give me a bit of time.

**Comment by knghtbrd** [comment] 2024-09-15 07:55
WHOA WHOA WHOA WHOA WHOA … I thought I had re-enabled OiTC when testing above, I had not.

I was wrong. Containerize set to open www.amazon.com in Amazon container plus OiTC set in implicit mode JUST OPENED EIGHT HUNDRED TABS before I killed it. Not kidding, eight hundred of OiTC and Containerize fighting each other, not even like MAC fighting with it. I had to kill -9 firefox FOUR TIMES to get it to stop opening new tabs. Data was lost. Holy crap, every time the profile starts it immediately starts opening tabs as fast as it can and doesn't respond to keypresses to try and get into settings to shut down the extension. I'm gonna have to try and delete it from my profile directory if I can and hope that works, because if I didn't I just lost my entire browser config on desktop.

Thankfully for once container-related stuff doesn't sync to mobile. 😬

**Comment by igorlogius** [comment] 2024-09-15 08:10
@silverwings15  
I see the issue(s) but i am not exactly sure what is happening here 

@knghtbrd 
Sorry if you are having issues too.


Seems like my confidence in the Exclusion mechanic was premature.
I suspect it has something todo with the redirects search engines like to use, which is causing these problems. I need to investigate this further.

**Comment by igorlogius** [comment] 2024-09-15 09:39
So far, i understand (one part) of the issue like this: 

2 (or more addons) react on same URL creation/navigations

OiTC in implicit mode, will try and immediately when a tab get a url to convert every None-Containerized tab into a Temp Container if the url is not on the Exclusion list.

MAC and Containerize both work the same way, they basically close the inital None-Containerized tab, when detecting an URL change that matches with one of their assinments. 

The problem is, that both addons are acting on the inital None-Containerized 
tab.  

Both will try to close it, which isn't a problem AFAICS, but also both, will try and create a new tab within a container (one in a temp container and the other in an assigned container)  That leaves us with 2 tabs. 

@knghtbrd 
I havend full understood how the infinitiv tab creatation happend.

The only real solution i see at the moment add  tab assinment function (like MAC or containerize has to OiTC so people dont need to use MAC or containerize, which would resolve this issue.

**Comment by igorlogius** [comment] 2024-09-15 19:13
version `1.1.43` looks promising. 

At least i did not notice any issues when using MAC and OiTC's ignore list.

**Comment by igorlogius** [comment] 2024-09-16 09:42
@silverwings15 

Can you confirm that the new version fixes your previously mentioned issue?

**Comment by knghtbrd** [comment] 2024-09-16 20:14
I got a bit distracted by … life … this weekend, will create a new profile and try to break stuff tonight!

**Comment by silverwings15** [comment] 2024-09-16 20:34
@igorlogius so far so good.. will keep you updated

**Comment by igorlogius** [comment] 2024-09-16 20:57
@knghtbrd 
@silverwings15 

Please test responsibly and dont damage your system !
Using a new profile is the safest route. I know this tedious to setup especially if tests involve issue with more than one addon. 

So thank for you help. I really appreciate it!

**Comment by igorlogius** [comment] 2024-09-19 18:04
closing and waiting on bug reports in new tickets ;)

**Closed by igorlogius** 2024-09-19 18:04 UTC
Labels: 🪲 Bug
