### ISSUE TITLE
Open in Temp Container: deletion delay / prevent sync of Temp Containers 

### ISSUE THREAD

**Issue by gabeweb** [igorlogius/igorlogius#50] opened 2024-09-15 17:59 UTC
### Question

Hi, is the "Container deletion delay" setting missed or something?

I am currently a user of [Temporary Containers](https://addons.mozilla.org/es/firefox/addon/temporary-containers/) by [stoically](https://addons.mozilla.org/es/firefox/user/13470938), but this extension has not been updated for years.

However, in your extension the option to modify the delay when deleting the temporary tab does not appear (and that is what prevents me from stopping using Temporary Containers because of your extension, which is more current).

Thanks.

**Comment by igorlogius** [comment] 2024-09-15 18:44
@gabeweb 

Greeting. 

As for a while now, OiTC takes care of container removal internally.

The deletion delay was once an option, but at a certain point it was removed from the UI, because i did not see a usecase for why a user should manually need to consern himself with when a temporary container should be removed.

**Comment by gabeweb** [comment] 2024-09-16 01:58
Hi @igorlogius,

Thank you for the reply.

> The deletion delay was once an option, but at a certain point it was removed from the UI, because i did not see a usecase for why a user should consern himself with when a temporary container is removed.

Well, I would like to be able to change the deletion time of the temporary container, because I think 30 seconds (that seems to be the default time), in my case, is an "eternity" when using Firefox Portable away from home. With the other extension, I have the time set to zero, and the container is automatically deleted.

**Comment by igorlogius** [comment] 2024-09-16 06:35
@gabeweb 

> I think 30 seconds ... , in my case, is an "eternity" 

Yes 30 seconds is the default, but i dont see how you would even notice the existing Temp Containers if you dont constantly access container specific sub menus or have some other addon monitors and visualizes them. So i really dont understand your usecase here, sorry.

**Comment by gabeweb** [comment] 2024-09-16 20:54
> but i dont see how you would even notice the existing Temp Containers if you dont constantly access container specific sub menus or have some other addon monitors and visualizes them.

Firefox Sync (and in limited network conditions, both history and currently created containers may remain in the Firefox cloud). It happened to me with the other extension. I suddenly close Firefox but Sync did not delete the history or the container in time, even though the container was already deleted (immediately). So those default 30 seconds in this extension would translate into an additional 30 seconds (worst case) until Firefox Sync completely deletes all the data.

One seeks comfort in a certain way with this extension of not having to open another private window (separately), and for it to behave as closely as possible to a private window, but in a tab.

**Comment by igorlogius** [comment] 2024-09-16 22:02
I see. That is indeed an issue, but as far as i understand it the deletion delay is really just a incomplete stop-gap solution, since some temp containers would still get synced if they just existed for long enough / if the sync algo runs at an unlucky time before you shut down your browser. 
 
IMO, this usecase seems to warrent a feature request to https://connect.mozilla.org or directly to the https://bugzilla.mozilla.org 

Something in the line of: 

[Feature Request] add a attribute to control syncing of a contextualIdentitiy (aka. container)
[Component: WebExtensions API ]

<add usecase description here>

Suggestion: 

`sync`: (optional, default: true)
A boolean value that allows fine grained control about if a container should be included when container syncing is enabled. 

Should be usable in `create` and `update` functions

Example:  how to prevent syncing for a created container
```javascript
let createContext = browser.contextualIdentities.create({
     sync: false 
})
```

- https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/create

Example: how to change the syncing status of a container later after creation 

```javascript
browser.contextualIdentities.update(
  cookieStoreId,           // string
  {
    sync: true
  }
)
```
- https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/update

**Comment by igorlogius** [comment] 2024-09-16 22:11
Seems like you arent the first one having issues with syncing temp containers either

https://old.reddit.com/r/firefox/comments/oeyb0s/how_to_delete_firefox_multiaccount_containers/

**Comment by gabeweb** [comment] 2024-09-17 00:08
@igorlogius Wow, you have left me shocked with the explanation (and that the problem goes further, due to technical issues of Firefox itself).

Well yes, the thing is a little more serious in slow connection situations (when I work away from home and have to visit some clients), where locally I may have deleted the temporary container along with the history, but still in Firefox Sync the changes have not been processed. When the connection is stable, I have no problems and in the profiles I have configured, no duplicate containers are shown or anything like that.

**Comment by igorlogius** [comment] 2024-09-17 01:06
@gabeweb 

Well, i am mostly speculating ... i could be wrong about a lot of things here (like how the sync algo is processing the containers). I am not familiar with the exact implementation of how this is handled. 

But your descripton about the connection state seems to indicate, that Fx sync is "just    distributing" all containers in "fixed interalls" to other connected clients.

This would explain the existence of the containers on other systems.

When the deletion of a container can not be finalized because the browser is sudenlly shutdown with still intact temp containers for example  the container deletion  information should not  get propaged to other clients and the container should continue to exist on the other clients until deletion process can be finished, likely on the next browser restart, by the addons cleanup routine.

Duplicate containers arent really the main issue here as far as i can tell ... unless maybe you have the same addon on multiple devices enabled. 

At the moment i cant really say if there is a reliable way to handle this.
I'd need to discuss this with someone that knows more about the sync algo and maybe other firefox internal stuff. 

The delay manipulation still seems like an hacky workaround ... but if it works 99% of the time ... i could maybe see to re-add the option. 

I'll have to think about this for a bit. And i'll have to try and remember if there was another reason why i set the deletion delay to be so high, because at the back of my mind i feel like there was a reason for that too, which i seem to have forgotten and which i fear will come back and bite-me in the ass as again later.

**Comment by igorlogius** [comment] 2024-09-19 18:16
@gabeweb 

fyi: I lowered the deletion delay down to 10 seconds, but i wont be exposing the option in the UI, since i dont see it as a solution for the actual problem.

I'll leave this issue open for now, in case anyone else has a similar issue with sync.

If i have some time i might also open a ticket on https://bugzilla.mozilla.org to maybe discuss/present this problem/usecase for containers to the firefox developers.

**Comment by gabeweb** [comment] 2024-09-20 17:20
@igorlogius

Hi again, I'm not sure if I can add another little thing that I noticed here or in another post, regarding the deletion of browsing history (and I think it may be related to the same delay).

History entries are not automatically deleted as long as a tab is not maintained with the temporary container, that is, until I wait for the default time to pass, I cannot close the tab without deleting the history first.

With the other extension I don't have that problem, regardless of whether I have it configured to delete it immediately when closing the tab or after a certain time. Here in this case, if I close the tab, the extension apparently stops counting time when closing the tab with the temporary container (so I have to manually delete the history).

**Comment by igorlogius** [comment] 2024-09-20 17:55
@gabeweb 

I'd request that you open a separate bug-issue containing the required steps for me to reproduce the deletion problem.

**Comment by igorlogius** [comment] 2024-10-22 09:27
closing the issue because there is nothing i can do about the situation at the moment

**Closed by igorlogius** 2024-10-22 09:27 UTC
Labels: 💡 Suggestion, 🚧 Blocked
