### ISSUE TITLE
LocalStorage Editor: add scheduled export function

### ISSUE THREAD

**Issue by vcfee** [igorlogius/igorlogius#55] opened 2024-10-17 04:07 UTC
### Description

can you add a scheduled export feature to this plugin. Sometimes, when the browser is accidentally closed, the session is lost.

**Comment by igorlogius** [comment] 2024-10-17 11:34
Hi, thanks for taking the time to open this issue.

Can you elaborate on what you are doing and what the problem is a bit more?

As far as i understand, the localstorage data should normally not be cleared when you restart your browser except when you have your browser configured to delete session information after closing (private browsing mode?).  Or do you mean the data that is currently being entered in the toolbar popup? 

Thanks in advance.

**Comment by vcfee** [comment] 2024-10-23 08:17
Sorry for the late reply, I've been busy recently. I'm currently dealing with a website where the data is stored in the session, and it contains a JWT formatted token. The session is lost when the browser is closed. However, if I use a recently saved session, I can re-enter without having to log in again.
![图片](https://github.com/user-attachments/assets/d03b63a5-02de-4514-beb5-c4d573f7a969)

**Comment by igorlogius** [comment] 2024-10-23 08:46
> The session is lost when the browser is closed.

AFAIK, this shouldn't be the default behaviour.
Do you have your browser setup (for testing the website) to start with a new profile or a private window so it always deletes the session data on close?

**Closed** 2024-10-24 11:17 UTC
Labels: 💡 Suggestion
